language: php

sudo: true

services:
    - docker

branches:
    only:
        - master

matrix:
    include:
        - php: '7.3'
        - php: '7.3'
          env: lint=1

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - export PATH="$PATH:$HOME/.composer/vendor/bin:./vendor/bin"

install:
    - make install

script:
    - export SYMFONY_DEPRECATIONS_HELPER=strict
    - if [[ $lint ]]; then make security-check cs-full-check phpstan; fi
    - cp config.php.dist config.php
    - bin/hubkit.php self-diagnose
